#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""bl_upgrade.py — LiteBootLoader 上位机 v1.4.0（独立仓库 LiteBootUpgrader）

协议见 docs/protocol.md：
  SOF(AA 55) | VER(01) | CMD | SEQ | LEN(LE16) | DATA(0..256B) | CRC16(LE16,MODBUS) | EOF(55 AA)
CRC 覆盖 VER..DATA；响应 CMD = 请求 CMD|0x80，DATA[0] = 状态码。
连接类型：--conn serial（有线串口，默认）| bt（蓝牙 SPP/HC-05，打开失败自动重试）；
模块需一次性 AT 配置数据模式到 115200（主仓 docs/dev/bluetooth_notes.md §5）。

签名验签（1.4.0，ADR-020）：`keygen` 子命令生成 P-256 测试密钥对（私钥 PEM +
公钥本地头 bl_sign_pubkey_local.h——任何形态不入库）；`upgrade --key <pem>` 在
写块完成后改发 0x11 VERIFY_SIGNED（固件需 BL_SIGN_EN=1 且公钥配对，auth 置位
方可跳转；篡改镜像将回 SIGN_ERROR 且不持久化）。

主机侧重试约定（protocol.md §6）：单命令响应超时 1000 ms（ERASE/VERIFY 5000 ms），
超时后重发至多 3 次尝试（首发 1 + 重发 ≤2），重试间隔 2.2 s（等待 BL 帧内 2000 ms 超时复位解析器）。
upgrade 会自动识别对端：若 APP 正在运行，先走"请求回 BL"流程（SET_META bl_request）
再升级——从任意状态一条命令完成升级。

依赖隔离（建议隔离运行，勿直接 pip install 到全局）：
  uv run --python 3.12 --with pyserial bl_upgrade.py selftest --port COM4
  签名功能（keygen / upgrade --key）另需：
  uv run --python 3.12 --with pyserial --with cryptography bl_upgrade.py keygen
"""
import argparse
import struct
import sys
import time
import zlib
from pathlib import Path

try:
    import serial
except ImportError:
    sys.exit("缺少 pyserial：请用 uv run --python 3.12 --with pyserial ... 运行")

SOF = b"\xAA\x55"
EOF = b"\x55\xAA"
VER = 0x01
CMD = {"ping": 0x01, "info": 0x02, "erase": 0x03, "write": 0x04,
       "verify": 0x05, "set_meta": 0x06, "get_meta": 0x07,
       "jump": 0x08, "reset": 0x09, "ota": 0x10, "verify_signed": 0x11}
STATUS = {0x00: "OK", 0x01: "CRC_ERROR", 0x02: "FLASH_ERROR",
          0x03: "RANGE_ERROR", 0x04: "STATE_ERROR", 0x05: "TIMEOUT",
          0x06: "SIGN_ERROR"}
APP_SIZE = 0xB800          # 46 KiB（board_config.h BL_APP_SIZE）
CHUNK_PAYLOAD = 252        # DATA ≤ 256B，WRITE_CHUNK 头占 4B

# 主机侧重试约定（protocol.md §6）：超时重发至多 3 次尝试，间隔 2.2 s 等 BL 解析器复位
RETRY_ATTEMPTS = 3
RETRY_DELAY = 2.2
T_DEFAULT, T_ERASE, T_VERIFY = 1.0, 5.0, 5.0

VERSION = "1.4.0"          # LiteBootUpgrader 版本（--version 与 description 共用）

# ---- 签名验签（1.4.0，ADR-020；cryptography 懒加载，非签名路径零依赖） ----
CRYPTO_HINT = ("uv run --python 3.12 --with pyserial --with cryptography "
               "bl_upgrade.py ...")


def _require_crypto():
    """签名功能专用：cryptography 缺失时友好退出（不污染非签名路径）。"""
    try:
        from cryptography.hazmat.primitives import hashes, serialization
        from cryptography.hazmat.primitives.asymmetric import ec
        from cryptography.hazmat.primitives.asymmetric.utils import \
            decode_dss_signature
        return hashes, serialization, ec, decode_dss_signature
    except ImportError:
        sys.exit(f"[X] 缺少 cryptography：签名功能请用 {CRYPTO_HINT} 运行")


def cmd_keygen(out_key: str, out_header: str | None) -> int:
    """生成 P-256 测试密钥对：私钥 PEM（本地保管，不入库）+ 公钥本地头
    （bl_sign_pubkey_local.h 格式，与固件 core/bl_sign.c 消费约定一致；
    注释刻意全 ASCII——armcc 以本地编码读源文件，UTF-8 中文注释会吞换行）。"""
    hashes, serialization, ec, _dec = _require_crypto()
    key = ec.generate_private_key(ec.SECP256R1())
    pn = key.public_key().public_numbers()
    raw = pn.x.to_bytes(32, "big") + pn.y.to_bytes(32, "big")   # Qx‖Qy 大端 64B
    lines = []
    for i in range(0, 64, 8):
        chunk = ", ".join(f"0x{b:02X}" for b in raw[i:i + 8])
        lines.append("    " + chunk + ("" if i == 56 else ", \\"))
    header = (
        "/* bl_sign_pubkey_local.h -- generated by LiteBootUpgrader keygen\n"
        " * P-256 public key, Qx||Qy big-endian raw, 64 bytes total (ADR-020).\n"
        " * LOCAL ONLY: kept out of git via .gitignore. Keep the matching\n"
        " * private key safe; rotate before production. */\n\n"
        "#ifndef BL_SIGN_PUBKEY_LOCAL_H\n"
        "#define BL_SIGN_PUBKEY_LOCAL_H\n\n"
        "#define BL_SIGN_PUBKEY_BYTES \\\n" + "\n".join(lines) + "\n\n"
        "#endif /* BL_SIGN_PUBKEY_LOCAL_H */\n")
    key_path = Path(out_key)
    key_path.write_bytes(key.private_bytes(
        serialization.Encoding.PEM, serialization.PrivateFormat.PKCS8,
        serialization.NoEncryption()))
    print(f"[OK] 私钥：{key_path}（本地妥善保管，勿提交/勿外发；量产前必须换正式密钥）")
    if out_header:
        hp = Path(out_header)
        hp.parent.mkdir(parents=True, exist_ok=True)
        hp.write_text(header, encoding="utf-8", newline="\n")
        print(f"[OK] 公钥头：{hp}（写入固件仓芯片端口目录；该路径须在 .gitignore）")
    else:
        print(header, end="")
        print("[提示] 用 --out-header <路径> 直接写入固件仓芯片端口目录")
    print("[下一步] 固件 board_config.h 置 BL_SIGN_EN=1 全量重建（编译日志应出现签名警告行）；"
          f"升级：upgrade <镜像> --key {key_path}")
    return 0


def sign_image_bytes(img: bytes, key_path: str) -> bytes:
    """对填充后镜像 ECDSA P-256 签名（库内 SHA-256，≡对镜像摘要签名，§5.11），
    返回 r‖s 定宽大端 64B——与固件 uECC 默认大端字节序直通。"""
    hashes, serialization, ec, decode_dss_signature = _require_crypto()
    try:
        key = serialization.load_pem_private_key(Path(key_path).read_bytes(),
                                                 password=None)
    except OSError as e:
        sys.exit(f"[X] 读取私钥失败：{e}")
    except ValueError as e:
        sys.exit(f"[X] 私钥文件不是合法 PEM：{e}")
    if not isinstance(key, ec.EllipticCurvePrivateKey) or not isinstance(
            key.curve, ec.SECP256R1):
        sys.exit("[X] 私钥不是 EC P-256 密钥")
    der = key.sign(img, ec.ECDSA(hashes.SHA256()))
    r, s = decode_dss_signature(der)
    return r.to_bytes(32, "big") + s.to_bytes(32, "big")


def crc16_modbus(data: bytes) -> int:
    crc = 0xFFFF
    for b in data:
        crc ^= b
        for _ in range(8):
            crc = (crc >> 1) ^ 0xA001 if (crc & 1) else (crc >> 1)
    return crc


def build_frame(cmd: int, seq: int, data: bytes = b"") -> bytes:
    if len(data) > 256:
        # LEN 字段只有 2 B 且协议上限 256：超长会生成 LEN 与实际不符的帧
        # （review 2026-09-27 P3）
        raise ValueError(f"DATA 超长：{len(data)}B > 协议上限 256B（protocol.md §4）")
    head = bytes([VER, cmd, seq, len(data) & 0xFF, (len(data) >> 8) & 0xFF])
    c = crc16_modbus(head + data)
    return SOF + head + data + bytes([c & 0xFF, (c >> 8) & 0xFF]) + EOF


def st_name(st: int) -> str:
    return STATUS.get(st, f"0x{st:02X}")


def _resp_status(r, what: str):
    """安全取响应状态字节：无响应返回 None，DATA 过短抛 RuntimeError（对端异常，
    review 2026-09-27 P2——畸形短响应不再以 IndexError 栈回溯退出）。"""
    if r is None:
        return None
    if len(r["data"]) < 1:
        raise RuntimeError(f"{what} 响应 DATA 为空（对端异常）")
    return r["data"][0]


OPEN_ATTEMPTS_BT = 3       # 蓝牙 SPP 打开重试次数（重连竞态窗口）
OPEN_RETRY_DELAY = 0.5     # 蓝牙打开重试间隔（秒）


class BootLoader:
    def __init__(self, port: str, baud: int = 115200, pace_ms: int = 0,
                 conn: str = "serial"):
        # conn="bt"：蓝牙 SPP 偶发打开失败（重连竞态），带重试；有线保持原行为
        last = None
        self.s = None
        for _ in range(OPEN_ATTEMPTS_BT if conn == "bt" else 1):
            try:
                self.s = serial.Serial(port, baud, timeout=0.05, write_timeout=2.0)
                break
            except serial.SerialException as e:
                last = e
                if conn == "bt":
                    time.sleep(OPEN_RETRY_DELAY)
        if self.s is None:
            sys.exit(f"[X] 打开 {port} 失败：{last}（若 UartAssist 等已占用串口请先关闭；"
                     "蓝牙模式请确认模块上电且已配对，重试仍失败可重插模块）")
        self.buf = b""
        self.seq = 0
        self.noise = b""          # 无法成帧的字节（日志/心跳/重启横幅）
        self.sent_bytes = 0       # 本次连接累计发送字节（含坏帧）
        self.expected_delivered = 0  # 本次连接预期送达的有效帧数
        self.pace = pace_ms       # 命令间延时（ms），用于时序假设验证

    def _noise(self, b: bytes):
        if b:
            self.noise = (self.noise + b)[-4096:]

    def saw_reboot_banner(self) -> bool:
        return b"upgrade mode" in self.noise or b"LiteBL" in self.noise

    def cmd(self, name: str, data: bytes = b"", timeout: float = 1.0):
        """发送命令并等待响应；返回 {'cmd','seq','data'} 或 None（超时）。
        SEQ 错位与 CMD 不匹配的帧均视为异己帧丢弃并继续等到 deadline
        （review 2026-09-27 P2：迟到/错配响应不再中断流程），由重试层兜底；
        全命令幂等，丢弃不会产生副作用。"""
        self.seq = (self.seq + 1) & 0xFF
        f = build_frame(CMD[name], self.seq, data)
        self.sent_bytes += len(f)
        self.expected_delivered += 1
        self.s.write(f)
        self.s.flush()
        if self.pace:
            time.sleep(self.pace / 1000.0)
        deadline = time.time() + timeout
        while True:
            remaining = deadline - time.time()
            if remaining <= 0:
                return None
            r = self.recv_frame(remaining)
            if r is None:
                return None
            if r["cmd"] != (CMD[name] | 0x80):
                print(f"    [!] CMD 错位：期望 {CMD[name] | 0x80:#04x}，"
                      f"收到 {r['cmd']:#04x}（丢弃继续等待）")
                continue
            if r["seq"] == self.seq:
                return r
            print(f"    [!] SEQ 错位：期望 {self.seq}，收到 {r['seq']}"
                  f"（疑似迟到响应，丢弃继续等待）")

    def cmd_retry(self, name: str, data: bytes = b"", timeout: float = 1.0,
                  attempts: int = RETRY_ATTEMPTS, log=print):
        """带重试的命令：超时后等 ≥2.1s（BL 帧内超时复位半帧）再重发。
        收到状态响应（含错误码）不重试——那是真实答复。"""
        for i in range(attempts):
            r = self.cmd(name, data, timeout=timeout)
            if r is not None:
                return r
            if i < attempts - 1:
                log(f"    [!] {name} 超时，{RETRY_DELAY:.1f}s 后重发（{i + 2}/{attempts}）")
                time.sleep(RETRY_DELAY)
        return None

    def send_raw(self, frame: bytes):
        self.sent_bytes += len(frame)
        self.s.write(frame)
        self.s.flush()

    def recv_frame(self, timeout: float):
        """帧同步解析：跳过日志/心跳噪声，CRC 或边界不合法则逐字节重同步。"""
        deadline = time.time() + timeout
        while time.time() < deadline:
            chunk = self.s.read(256)
            if chunk:
                self.buf += chunk
            while True:
                idx = self.buf.find(SOF)
                if idx < 0:
                    if len(self.buf) > 1:
                        self._noise(self.buf[:-1])
                    self.buf = self.buf[-1:]   # 保留尾字节防 SOF 被截断
                    break
                if idx:
                    self._noise(self.buf[:idx])
                    self.buf = self.buf[idx:]
                if len(self.buf) < 7:
                    break
                ln = self.buf[5] | (self.buf[6] << 8)
                if ln > 256:                   # 非法长度：伪 SOF，丢 1 字节
                    self.buf = self.buf[1:]
                    continue
                total = 11 + ln
                if len(self.buf) < total:
                    break
                frame, self.buf = self.buf[:total], self.buf[total:]
                body = frame[2:7 + ln]
                want = frame[7 + ln] | (frame[8 + ln] << 8)
                if (frame[2] == VER and frame[-2:] == EOF
                        and crc16_modbus(body) == want):
                    return {"cmd": frame[3], "seq": frame[4],
                            "data": frame[7:7 + ln]}
                self._noise(frame)         # 坏帧计入噪声，整帧丢弃即完成重同步
        return None


# ---- 响应解析 ----

def parse_info(d: bytes) -> str:
    if len(d) < 31:
        # 短响应防御（审计 2026-09-29 P3-2）：基础字段至少 31B（status+ver(4)+uid(12)
        # +flsz(2)+valid(1)+size/crc/seq(12)），否则 unpack_from(d,19) 越界；
        # 1B 状态响应通常是 APP 迷你响应器所答
        return (f"短响应（{len(d)}B，status={st_name(d[0]) if d else '空'}）"
                f"—— 对端疑似 APP 而非 BL")
    ma, mi, pa = d[1], d[2], d[3]
    uid = bytes(d[4:16])
    flsz = d[16] | (d[17] << 8)
    valid = d[18]
    size, crc, seq = struct.unpack_from("<III", d, 19)
    extra = ""
    if len(d) >= 39:
        rx, vf = struct.unpack_from("<II", d, 31)
        extra = f" rx={rx} vf={vf}"
    if len(d) >= 47:
        cfc, bto = struct.unpack_from("<II", d, 39)
        extra += f" crcfail={cfc} bytetimeout={bto}"
    if len(d) >= 51:
        (tpd,) = struct.unpack_from("<I", d, 47)
        extra += f" pend={tpd}"
    if len(d) >= 67:
        gap, tpend, tstate, tgot = struct.unpack_from("<IIII", d, 51)
        extra += (f" | 超时现场: 饥饿{gap}ms 缓冲{tpend}B 状态{tstate} 已收{tgot}")
    return (f"BL v{ma}.{mi}.{pa} flash={flsz}KB app_valid={valid} "
            f"app_size={size} app_crc={crc:#010x} seq={seq} "
            f"uid={uid.hex().upper()}{extra}")


def parse_meta(d: bytes) -> dict:
    """GET_META 响应 21B：status + seq(4) + flags(4) + ver(3) + size(4) + crc(4) + copy(1)"""
    if len(d) < 21:
        # 畸形短响应防御（review 2026-09-27 P2），与 parse_info 的短响应保护同类
        raise RuntimeError(f"GET_META 响应 DATA 过短：{len(d)}B < 21B（对端异常）")
    seq, flags = struct.unpack_from("<II", d, 1)
    ver = (d[9], d[10], d[11])
    size, crc = struct.unpack_from("<II", d, 12)
    return {"seq": seq, "flags": flags, "ver": ver,
            "size": size, "crc": crc, "active_copy": d[20]}


def meta_str(m: dict) -> str:
    return (f"seq={m['seq']} flags={m['flags']:#010x} "
            f"app_ver={m['ver'][0]}.{m['ver'][1]}.{m['ver'][2]} "
            f"size={m['size']} crc={m['crc']:#010x} copy={m['active_copy']}")


OTA_CHAN = {0: "有线 USART1", 1: "蓝牙 UART2"}


def parse_ota(d: bytes) -> str:
    """OTA_QUERY(0x10) 响应 DATA → 人读文本（protocol.md §5.10：22B 全量，status 首字节）。"""
    if len(d) < 1:
        return "ota: 空响应（对端异常）"
    if d[0] != 0x00:
        return f"ota: {st_name(d[0])}"
    if len(d) < 22:
        raise RuntimeError(f"OTA_QUERY 响应 DATA 过短：{len(d)}B < 22B（对端异常）")
    (_, b0, b1, b2, a0, a1, a2, valid, size, crc, seq, chan, bt) = struct.unpack(
        "<B3B3BBIIIBB", d[:22])
    return "\n".join((
        f"BL  v{b0}.{b1}.{b2}",
        f"APP v{a0}.{a1}.{a2}"
        f"（{'有效' if valid else '无效/无 APP'} size={size} crc={crc:#010x}）",
        f"meta_seq={seq} 通道={OTA_CHAN.get(chan, hex(chan))}"
        f" 蓝牙={'已连接' if bt else '未连接'}",
    ))


def verify_probe(bl: BootLoader, size: int, want_crc: int):
    """发送 VERIFY 并返回 (status, calc_crc, calc_size)。"""
    r = bl.cmd("verify", struct.pack("<II", size, want_crc), timeout=3.0)
    if r is None:
        return None, None, None
    if len(r["data"]) < 9:
        # status + calc_crc32 + calc_size 最少 9B（review 2026-09-27 P2）
        raise RuntimeError(f"verify 响应 DATA 过短：{len(r['data'])}B < 9B（对端异常）")
    st = r["data"][0]
    calc, csize = struct.unpack_from("<II", r["data"], 1)
    return st, calc, csize


def info_counters(bl: BootLoader):
    """读 GET_INFO 遥测计数器，返回 (rx, vf, crcfail, bytetimeout, pending) 或 None。"""
    r = bl.cmd("info")
    if r is not None and r["data"][0] == 0 and len(r["data"]) >= 51:
        return struct.unpack_from("<IIIII", r["data"], 31)
    return None


def timeout_detail(bl: BootLoader):
    """读最近一次帧内超时现场 [gap_ms, pending, state, got]，异常返回 None。"""
    r = bl.cmd("info")
    if r is not None and r["data"][0] == 0 and len(r["data"]) >= 67:
        return struct.unpack_from("<IIII", r["data"], 51)
    return None


# ---- selftest：升级流程硬件在环检验（二分定位版） ----

def selftest(bl: BootLoader) -> int:
    print(f"== 升级流程检验 selftest（{bl.s.port} @ {bl.s.baudrate}）==")
    results = []

    def step(name, ok, evidence):
        results.append(ok)
        print(f"[{'PASS' if ok else 'FAIL'}] {name}: {evidence}")

    # 运行起始快照：本次运行内做 rx/vf 差值，开机累计历史不影响判读
    c0 = info_counters(bl)
    bl.sent_bytes = 0
    bl.expected_delivered = 0

    # 1. PING
    r = bl.cmd("ping", timeout=1.0)
    step("PING", r is not None and r["data"][0] == 0 and r["data"][1] == VER,
         "无响应" if r is None else
         f"status={st_name(r['data'][0])} proto_ver={r['data'][1]:#04x}")

    # 2. ERASE_APP（46 页，预计 1~2s）
    t0 = time.time()
    r = bl.cmd("erase", timeout=8.0)
    step("ERASE_APP", r is not None and r["data"][0] == 0,
         "无响应" if r is None else
         f"status={st_name(r['data'][0])} 耗时={time.time() - t0:.2f}s")

    # 3. 零写入读路径探针：擦除后对全 0xFF 内容做 VERIFY。
    #    同时覆盖三件事：CRC32 实现与 zlib 一致性 / 擦除有效性 / Flash 读路径。
    for size in (1024, 512):
        want = zlib.crc32(b"\xFF" * size) & 0xFFFFFFFF
        st, calc, csize = verify_probe(bl, size, want)
        if st is None:
            step(f"读路径探针 verify({size},全FF)", False, "无响应")
        else:
            step(f"读路径探针 verify({size},全FF)", st == 0 and calc == want,
                 f"status={st_name(st)} calc_crc={calc:#010x}（zlib 期望={want:#010x}）"
                 f" calc_size={csize}")

    # 4. 最小写入：8B @0（8B = 固件 VERIFY 下界 protocol.md §5.5，1ba8416 加固：
    #    size<8 拒绝——原 4B 版本是对旧契约的滞后，2026-09-27 真机 14/15 实锤后对齐）
    pat = bytes((i * 7 + 0x5A) & 0xFF for i in range(512))
    bl.noise = b""
    t0 = time.time()
    r = bl.cmd("write", struct.pack("<I", 0) + pat[0:8], timeout=5.0)
    if r is None:
        verdict = "无响应（5s）"
        verdict += "；检测到启动横幅 → 芯片发生复位（IWDG？）" if bl.saw_reboot_banner() else "；未见启动横幅"
        step("WRITE 8B @0", False, verdict + " —— 探测芯片活性…")
        r2 = bl.cmd("ping", timeout=2.0)
        step("WRITE 后活性探测", r2 is not None,
             "芯片存活" if r2 is not None else "芯片仍无响应")
    else:
        step("WRITE 8B @0", r["data"][0] == 0,
             f"status={st_name(r['data'][0])} 耗时={time.time() - t0:.2f}s")

    # 5. 回读 8B：区分「写入失败」与「读回失真」
    want8 = zlib.crc32(pat[0:8]) & 0xFFFFFFFF
    ff8 = zlib.crc32(b"\xFF" * 8) & 0xFFFFFFFF
    st, calc, csize = verify_probe(bl, 8, want8)
    if st is None:
        step("VERIFY 8B 回读", False, "无响应")
    else:
        hint = "内容=图案 ✓" if calc == want8 else (
            f"内容≠图案（若={ff8:#010x} 则仍为全FF）")
        step("VERIFY 8B 回读", st == 0 and calc == want8,
             f"status={st_name(st)} calc_crc={calc:#010x}（图案={want8:#010x}）—— {hint}")

    # 6. 其余 504B 分块写入（与首块 8B 互不重叠——同址重编程会 PGERR）
    for off, payload in ((8, pat[8:252]), (252, pat[252:504]), (504, pat[504:512])):
        bl.noise = b""
        t0 = time.time()
        r = bl.cmd("write", struct.pack("<I", off) + payload, timeout=5.0)
        st = None if r is None else r["data"][0]
        if r is None:
            verdict = "无响应（5s）"
            verdict += "；检测到启动横幅 → 芯片发生复位（IWDG？）" if bl.saw_reboot_banner() else "；未见启动横幅"
            step(f"WRITE {len(payload)}B @{off}", False, verdict)
            c1 = info_counters(bl)   # 本次运行内的差值遥测
            if c1 and c0:
                drx, dvf = c1[0] - c0[0], c1[1] - c0[1]
                dcfc, dbto, dtpd = c1[2] - c0[2], c1[3] - c0[3], c1[4] - c0[4]
                lost = bl.sent_bytes - drx
                where = ("全部到达" if lost <= 0 else f"UART/中断层丢失 {lost}B")
                print(f"    遥测: 发 {bl.sent_bytes}B / 实收 {drx}B（{where}），"
                      f"送达 {dvf}/{bl.expected_delivered} 帧，"
                      f"crcfail+{dcfc}，bytetimeout+{dbto}，超时时缓冲有字节+{dtpd}")
            else:
                print("    遥测: GET_INFO 无响应，无法判读")
            det = timeout_detail(bl)
            if det:
                print(f"    超时现场: 饥饿 {det[0]}ms，缓冲待取 {det[1]}B，解析状态 {det[2]}，帧内已收 {det[3]}B")
        else:
            step(f"WRITE {len(payload)}B @{off}", st == 0,
                 f"status={st_name(st)} 耗时={time.time() - t0:.2f}s")

    # 7. 全量 512B 校验 + 持久化
    good = zlib.crc32(pat) & 0xFFFFFFFF
    st, calc, csize = verify_probe(bl, 512, good)
    step("VERIFY 512B 全量", st == 0 and calc == good,
         "无响应" if st is None else
         f"status={st_name(st)} calc_crc={calc:#010x}（zlib={good:#010x}）calc_size={csize}")

    # 8. GET_META 核对持久化
    r = bl.cmd("get_meta")
    m = parse_meta(r["data"]) if r is not None and r["data"][0] == 0 else None
    step("META 持久化", m is not None and m["size"] == 512 and m["crc"] == good,
         meta_str(m) if m else "无响应/状态异常")

    # 9. 越界防护：offset = APP_SIZE 应拒绝
    r = bl.cmd("write", struct.pack("<I", APP_SIZE) + b"\x00" * 4)
    step("WRITE 越界防护", r is not None and r["data"][0] == 0x03,
         "无响应" if r is None else
         f"status={st_name(r['data'][0])}（期望 RANGE_ERROR）")

    # 10. CRC 损坏帧应被静默丢弃
    bl.seq = (bl.seq + 1) & 0xFF
    f = bytearray(build_frame(CMD["ping"], bl.seq))
    f[7] ^= 0xFF                      # 破坏 CRC 低字节
    bl.send_raw(bytes(f))
    r = bl.recv_frame(0.5)
    step("坏 CRC 帧静默丢弃", r is None,
         "0.5s 无响应 ✓" if r is None else f"意外响应 data={r['data'].hex()}")

    # 11. SET_META bl_request 生命周期（解耦判定：只看 flags 往返）
    r1 = bl.cmd("set_meta", bytes([0x01, 0x01]))
    r2 = bl.cmd("get_meta")
    r3 = bl.cmd("set_meta", bytes([0x01, 0x00]))
    r4 = bl.cmd("get_meta")
    if None in (r1, r2, r3, r4):
        step("SET_META bl_request 生命周期", False, "存在无响应步骤")
    else:
        f1 = parse_meta(r2["data"])["flags"]
        f2 = parse_meta(r4["data"])["flags"]
        ok = (r1["data"][0] == 0 and r3["data"][0] == 0
              and (f1 & 1) == 1 and (f2 & 1) == 0)
        step("SET_META bl_request 生命周期", ok,
             f"set→flags={f1:#010x}，clear→flags={f2:#010x}（bit0 1→0）")

    # 12. JUMP_APP：无效 APP 应被拒绝且不跳转
    r = bl.cmd("jump")
    step("JUMP_APP 拒绝无效 APP", r is not None and r["data"][0] == 0x04,
         "无响应" if r is None else
         f"status={st_name(r['data'][0])}（期望 STATE_ERROR，未跳转）")

    n_pass = sum(results)
    print(f"== selftest 结果：{n_pass}/{len(results)} 通过 ==")
    return 0 if all(results) else 1


# ---- 单命令 ----

def ensure_bl(bl: BootLoader, log=print) -> bool:
    """确认对端处于 BL；APP 在跑则自动走'请求回 BL'流程（external_interface.md §5）。"""
    log("探测对端…")
    for attempt in range(RETRY_ATTEMPTS):
        r = bl.cmd("info", timeout=T_DEFAULT)
        if r is not None:
            st = _resp_status(r, "GET_INFO")
            if st == 0x00:
                log("对端 = BL ✓")
                return True
            if st == 0x03:      # APP 响应器只认 PING/SET_META，其余回 RANGE_ERROR
                log("对端 = APP，发送 bl_request 请求回 BL…")
                r2 = bl.cmd("set_meta", bytes([0x01, 0x01]), timeout=T_DEFAULT)
                r2st = _resp_status(r2, "SET_META")
                log("APP 已确认请求" if r2st == 0
                    else "APP 未按预期确认（继续等待复位）")
                log("等待复位进入 BL（1.6s）…")
                time.sleep(1.6)
                continue        # 重新探测
            log(f"[X] 对端响应异常 status={st_name(st)}")
            return False
        if attempt < RETRY_ATTEMPTS - 1:
            # 无响应可能是 BL 解析器卡在半帧，等帧内超时复位后再试
            log(f"    [!] 探测无响应，{RETRY_DELAY:.1f}s 后重试（{attempt + 2}/{RETRY_ATTEMPTS}）")
            time.sleep(RETRY_DELAY)
    log("[X] 无法确认对端为 BL")
    return False


def run_upgrade(bl: BootLoader, path: str, log=print, progress=None,
                key_path: str | None = None) -> int:
    """一键升级完整流程（protocol.md §7 主机侧约定的唯一实现）：
    ensure_bl → ERASE → 逐块 WRITE → VERIFY / VERIFY_SIGNED。
    key_path 非 None 时走签名校验（0x11，固件需 BL_SIGN_EN=1 且公钥配对）。
    progress(done, total) 在每个块成功后回调（GUI 用）；返回 0=成功。"""
    with open(path, "rb") as f:
        img = f.read()
    if len(img) == 0 or len(img) > APP_SIZE:
        raise ValueError(f"镜像大小 {len(img)} 超出 1B~{APP_SIZE}B")
    if len(img) % 4:
        img += b"\xFF" * (4 - len(img) % 4)     # VERIFY 要求 4 字节对齐
    crc = zlib.crc32(img) & 0xFFFFFFFF
    log(f"镜像 {len(img)}B crc32={crc:#010x}")

    if not ensure_bl(bl, log=log):
        return 1

    log("擦除 APP 区…")
    r = bl.cmd_retry("erase", timeout=T_ERASE, log=log)
    st = _resp_status(r, "erase")
    log("erase:", st_name(st) if st is not None else "无响应（重试耗尽）")
    if st is None or st:
        return 1
    total = len(img)
    for off in range(0, total, CHUNK_PAYLOAD):
        r = bl.cmd_retry("write", struct.pack("<I", off) + img[off:off + CHUNK_PAYLOAD],
                         timeout=2.0, log=log)
        st = _resp_status(r, "write")
        if st is None or st:
            log(f"write @{off} 失败: "
                f"{st_name(st) if st is not None else '无响应（重试耗尽）'}")
            return 1
        if progress:
            progress(min(off + CHUNK_PAYLOAD, total), total)
    if key_path:
        sig = sign_image_bytes(img, key_path)
        log("验签…（VERIFY_SIGNED，ADR-020）")
        r = bl.cmd_retry("verify_signed", struct.pack("<II", total, crc) + sig,
                         timeout=T_VERIFY, log=log)
        st = _resp_status(r, "verify_signed")
        if st == 0:
            if len(r["data"]) < 9:
                raise RuntimeError(f"verify_signed 响应 DATA 过短："
                                   f"{len(r['data'])}B < 9B（对端异常）")
            calc, csize = struct.unpack_from("<II", r["data"], 1)
            log(f"verify_signed: OK crc={calc:#010x} size={csize} "
                f"—— auth 置位，APP 就绪，可 jump")
            return 0
        log("verify_signed 失败:", st_name(st) if st is not None else "无响应（重试耗尽）")
        if st == 0x06:
            log("[!] SIGN_ERROR：镜像或签名与固件公钥不符——未持久化（auth=0，拒绝跳转）；"
                "确认固件为 BL_SIGN_EN=1 构建且 --key 与其公钥配对")
        return 1
    log("校验…")
    r = bl.cmd_retry("verify", struct.pack("<II", total, crc), timeout=T_VERIFY, log=log)
    st = _resp_status(r, "verify")
    if st == 0:
        if len(r["data"]) < 9:
            # status + calc_crc32 + calc_size 最少 9B（review 2026-09-27 P2）
            raise RuntimeError(f"verify 响应 DATA 过短：{len(r['data'])}B < 9B（对端异常）")
        calc, csize = struct.unpack_from("<II", r["data"], 1)
        log(f"verify: OK crc={calc:#010x} size={csize} —— APP 就绪，可 jump")
        return 0
    log("verify 失败:", st_name(st) if st is not None else "无响应（重试耗尽）")
    return 1


def cmd_upgrade(bl: BootLoader, path: str, key_path: str | None = None) -> int:
    try:
        return run_upgrade(bl, path, key_path=key_path)
    except ValueError as e:
        sys.exit(f"[X] {e}")
    except RuntimeError as e:
        sys.exit(f"[X] {e}")     # 对端异常响应的友好退出（review 2026-09-27 P2）
    except OSError as e:
        sys.exit(f"[X] 打开镜像失败：{e}")


def build_parser():
    ap = argparse.ArgumentParser(description=f"LiteBootLoader 上位机 v{VERSION}（LiteBootUpgrader）")
    ap.add_argument("command",
                    choices=["ping", "info", "meta", "erase", "verify",
                             "upgrade", "jump", "reset", "selftest",
                             "listen", "raw", "setmeta", "ota", "keygen"])
    ap.add_argument("arg", nargs="?", help="upgrade: 镜像文件；verify: size")
    ap.add_argument("arg2", nargs="?", help="verify: crc32 十六进制")
    ap.add_argument("--port", default="COM4")
    ap.add_argument("--baud", type=int, default=115200)
    ap.add_argument("--pace", type=int, default=0,
                    help="命令间插入延时（ms），用于时序假设验证")
    ap.add_argument("--conn", choices=["serial", "bt"], default="serial",
                    help="连接类型：serial=有线串口（默认）；bt=蓝牙 SPP（HC-05，"
                         "打开失败自动重试）")
    ap.add_argument("--key", help="upgrade：ECDSA P-256 私钥 PEM——启用签名校验"
                                 "（0x11 VERIFY_SIGNED，固件需 BL_SIGN_EN=1 且公钥配对）")
    ap.add_argument("--out-key", default="sign_test_key.pem",
                    help="keygen：私钥 PEM 输出路径（默认 ./sign_test_key.pem）")
    ap.add_argument("--out-header",
                    help="keygen：公钥本地头输出路径（bl_sign_pubkey_local.h，"
                         "指向固件仓芯片端口目录；缺省仅打印到 stdout）")
    ap.add_argument("--version", action="version",
                    version=f"LiteBootUpgrader v{VERSION}")
    return ap


def main():
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass
    a = build_parser().parse_args()

    if a.command == "selftest":
        sys.exit(selftest(BootLoader(a.port, a.baud, a.pace, a.conn)))
    if a.command == "keygen":
        sys.exit(cmd_keygen(a.out_key, a.out_header))

    bl = BootLoader(a.port, a.baud, a.pace, a.conn)
    try:
        if a.command == "ping":
            r = bl.cmd("ping")
            print("无响应" if r is None else
                  f"status={st_name(r['data'][0])} proto_ver={r['data'][1]:#04x}")
        elif a.command == "info":
            r = bl.cmd("info")
            print("无响应" if r is None else parse_info(r["data"]))
        elif a.command == "ota":
            r = bl.cmd("ota", timeout=2.0)
            if r is None:
                print("无响应")
            else:
                try:
                    print(parse_ota(r["data"]))
                except RuntimeError as e:
                    print(f"ota: {e}")
        elif a.command == "meta":
            r = bl.cmd("get_meta")
            print("无响应" if r is None else meta_str(parse_meta(r["data"])))
        elif a.command == "erase":
            t0 = time.time()
            r = bl.cmd("erase", timeout=8.0)
            print("无响应" if r is None else
                  f"erase: {st_name(r['data'][0])} 耗时={time.time() - t0:.2f}s")
        elif a.command == "upgrade":
            if not a.arg:
                sys.exit("用法：upgrade <镜像文件> [--key <pem>]")
            sys.exit(cmd_upgrade(bl, a.arg, key_path=a.key))
        elif a.command == "verify":
            if not a.arg or not a.arg2:
                sys.exit("用法：verify <size> <crc32_hex>")
            r = bl.cmd("verify", struct.pack("<II", int(a.arg, 0), int(a.arg2, 16)),
                       timeout=3.0)
            print("无响应" if r is None else
                  f"verify: {st_name(r['data'][0])}")
        elif a.command == "listen":
            secs = float(a.arg) if a.arg else 3.0
            t0 = time.time()
            buf = bytearray()
            while time.time() - t0 < secs:
                chunk = bl.s.read(256)
                if chunk:
                    buf += chunk
            text = buf.decode("utf-8", "replace")
            if text.strip():
                print(text, end="")
            print(f"({secs:.0f}s 监听结束)")
        elif a.command == "raw":
            if not a.arg:
                sys.exit("用法：raw <hex 字节，如 42>")
            data = bytes.fromhex(a.arg.replace(" ", ""))
            bl.send_raw(data)
            print(f"已发送 {len(data)}B 原始字节")
        elif a.command == "setmeta":
            if not a.arg or not a.arg2:
                sys.exit("用法：setmeta <field_hex> <value_hex>")
            r = bl.cmd("set_meta", bytes([int(a.arg, 16), int(a.arg2, 16)]))
            print("无响应" if r is None else
                  f"set_meta({a.arg},{a.arg2}): {st_name(r['data'][0])}")
            t0 = time.time()
            buf = bytearray()
            while time.time() - t0 < 3.0:
                chunk = bl.s.read(256)
                if chunk:
                    buf += chunk
            text = buf.decode("utf-8", "replace")
            if text.strip():
                print("--- 后续串口输出 ---\n" + text, end="")
        elif a.command in ("jump", "reset"):
            follow = 6.0 if a.command == "reset" else 2.5
            r = bl.cmd(a.command, timeout=2.0)
            if r is None:
                print(f"{a.command}: 无响应")
                return
            print(f"{a.command}: {st_name(r['data'][0])}"
                  + ("（APP 无效被拒绝）" if r["data"][0] == 0x04 else ""))
            if r["data"][0] != 0x00:
                return
            t0 = time.time()
            buf = bytearray()
            while time.time() - t0 < follow:
                chunk = bl.s.read(256)
                if chunk:
                    buf += chunk
            text = buf.decode("utf-8", "replace")
            if text.strip():
                print("--- 串口输出 ---\n" + text, end="")
    except (RuntimeError, IndexError) as e:
        # 对端返回 CRC 合法但长度异常的响应时的兜底（审计 2026-09-29 P3-2）：
        # 现网 BL/APP 不会产生此类响应，友好退出而非栈回溯
        sys.exit(f"[X] {e}")


if __name__ == "__main__":
    main()
